#!/bin/sh

# Author: Timo Jyrinki <timo.jyrinki@canonical.com>
# Run this file to create a package for vivid overlay that contains only the single required python script.

sed -i "1 s/ubuntu\([0-9]\+\)/ubuntu\1~vivid1/" debian/changelog
sed -i "1 s/UNRELEASED/vivid/" debian/changelog
sed -i "1 s/xenial/vivid/" debian/changelog
sed -i "1 s/yakkety/vivid/" debian/changelog
dch -r 'Build for vivid'
cp -a debian/control.vivid debian/control
sed -i 's/with=golang,python3/with=python3/' debian/rules
sed -i 's/golang/pybuild/' debian/rules
# complains if not removing build system completely..
sed -i 's/--buildsystem=pybuild //' debian/rules
#debuild -S -sa 
